// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortableAgent.Persistence.Sqlite;

#nullable disable

namespace PortableAgent.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(PortableAgentDbContext))]
    [Migration("20260927044802_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PortableAgent.Persistence.Sqlite.Entities.ExecutionEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("ExecutionEvents", (string)null);
                });

            modelBuilder.Entity("PortableAgent.Persistence.Sqlite.Entities.RunStateEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeDefinitionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("RunId");

                    b.ToTable("Runs", (string)null);
                });

            modelBuilder.Entity("PortableAgent.Persistence.Sqlite.Entities.ExecutionEventEntity", b =>
                {
                    b.HasOne("PortableAgent.Persistence.Sqlite.Entities.RunStateEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
